### PR TITLE
skip or emit only certain events on the :cont in a trigger

### PR DESCRIPTION
**Pull request by zeeshanlakhani**
@josevalim figured that it'd be easier to push this here for discussion!

### CODE REVIEW

**Comment by josevalim** [comment]
This is perfect. We just need a test and update the docs and we should be good to go. :heart:

**Comment by zeeshanlakhani** [comment]
@josevalim great. I can do both. a mini custom trigger as a test good enough?

**Comment by josevalim** [comment]
@zeeshanlakhani yup!

**Comment by zeeshanlakhani** [comment]
@josevalim doc updated and tests added... lmk if there's anything more I should update and/or make clearer.

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
