### PR TITLE
Explain batching when describing Flow.partition

### PR DESCRIPTION
**Pull request by Arkham**
Should fix https://github.com/elixir-lang/flow/issues/21

### CODE REVIEW

**Comment by josevalim** [comment]
I have added a new comment on https://github.com/elixir-lang/flow/issues/21#issuecomment-301113394. You can show the issue by setting max_demand on from_enumerable. :)

**Comment by Arkham** [comment]
Thanks so much, just updated it and realised it's already written in the doc for `from_enumerable`, but I think in this way it's a better experience for the first time reader.

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
